const foodItems = [
  { name: "Apple", category: "Fruits", price: 0.5, quantity_type: "Each", emoji: "🍎" },
  { name: "Banana", category: "Fruits", price: 0.3, quantity_type: "Each", emoji: "🍌" },
  { name: "Orange", category: "Fruits", price: 0.6, quantity_type: "Each", emoji: "🍊" },
  { name: "Strawberry", category: "Fruits", price: 3.5, quantity_type: "Box", emoji: "🍓" },
  { name: "Blueberries", category: "Fruits", price: 3.0, quantity_type: "Box", emoji: "🫐" },
  { name: "Grapes", category: "Fruits", price: 2.5, quantity_type: "Lb", emoji: "🍇" },
  { name: "Watermelon", category: "Fruits", price: 5.0, quantity_type: "Each", emoji: "🍉" },
  { name: "Pineapple", category: "Fruits", price: 3.0, quantity_type: "Each", emoji: "🍍" },
  { name: "Mango", category: "Fruits", price: 1.2, quantity_type: "Each", emoji: "🥭" },
  { name: "Avocado", category: "Fruits", price: 1.5, quantity_type: "Each", emoji: "🥑" },
  { name: "Lemon", category: "Fruits", price: 0.5, quantity_type: "Each", emoji: "🍋" },
  { name: "Peach", category: "Fruits", price: 1.0, quantity_type: "Each", emoji: "🍑" },

  { name: "Broccoli", category: "Vegetables", price: 1.2, quantity_type: "Bunch", emoji: "🥦" },
  { name: "Carrot", category: "Vegetables", price: 0.8, quantity_type: "Lb", emoji: "🥕" },
  { name: "Spinach", category: "Vegetables", price: 2.0, quantity_type: "Bag", emoji: "🥬" },
  { name: "Potato", category: "Vegetables", price: 0.4, quantity_type: "Lb", emoji: "🥔" },
  { name: "Lettuce", category: "Vegetables", price: 1.5, quantity_type: "Each", emoji: "🥬" },
  { name: "Tomato", category: "Vegetables", price: 1.2, quantity_type: "Lb", emoji: "🍅" },
  { name: "Cucumber", category: "Vegetables", price: 0.9, quantity_type: "Each", emoji: "🥒" },
  { name: "Onion", category: "Vegetables", price: 0.6, quantity_type: "Lb", emoji: "🧅" },
  { name: "Garlic", category: "Vegetables", price: 0.5, quantity_type: "Each", emoji: "🧄" },
  { name: "Bell Pepper", category: "Vegetables", price: 1.0, quantity_type: "Each", emoji: "🫑" },
  { name: "Kale", category: "Vegetables", price: 2.2, quantity_type: "Bunch", emoji: "🥬" },
  { name: "Zucchini", category: "Vegetables", price: 1.1, quantity_type: "Each", emoji: "🥒" },
  { name: "Mushrooms", category: "Vegetables", price: 2.5, quantity_type: "Box", emoji: "🍄" },

  { name: "Bread", category: "Bakery", price: 2.0, quantity_type: "Loaf", emoji: "🍞" },
  { name: "Bagel", category: "Bakery", price: 1.5, quantity_type: "Each", emoji: "🥯" },
  { name: "Croissant", category: "Bakery", price: 2.5, quantity_type: "Each", emoji: "🥐" },
  { name: "Tortilla", category: "Bakery", price: 2.5, quantity_type: "Bag", emoji: "🌮" },
  { name: "Muffin", category: "Bakery", price: 1.8, quantity_type: "Each", emoji: "🧁" },
  { name: "Baguette", category: "Bakery", price: 2.2, quantity_type: "Each", emoji: "🥖" },

  { name: "Milk", category: "Dairy", price: 3.0, quantity_type: "Gallon", emoji: "🥛" },
  { name: "Cheddar Cheese", category: "Dairy", price: 4.0, quantity_type: "Lb", emoji: "🧀" },
  { name: "Yogurt", category: "Dairy", price: 1.0, quantity_type: "Cup", emoji: "🥣" },
  { name: "Butter", category: "Dairy", price: 3.5, quantity_type: "Lb", emoji: "🧈" },
  { name: "Cream Cheese", category: "Dairy", price: 2.5, quantity_type: "Each", emoji: "🧀" },

  { name: "Chicken Breast", category: "Meat", price: 5.5, quantity_type: "Lb", emoji: "🍗" },
  { name: "Ground Beef", category: "Meat", price: 6.0, quantity_type: "Lb", emoji: "🥩" },
  { name: "Pork Chop", category: "Meat", price: 5.0, quantity_type: "Lb", emoji: "🥩" },
  { name: "Bacon", category: "Meat", price: 4.5, quantity_type: "Lb", emoji: "🥓" },
  { name: "Sausage", category: "Meat", price: 4.0, quantity_type: "Lb", emoji: "🌭" },
  { name: "Turkey Breast", category: "Meat", price: 5.2, quantity_type: "Lb", emoji: "🦃" },
  { name: "Ground Turkey", category: "Meat", price: 5.0, quantity_type: "Lb", emoji: "🍗" },
  { name: "Lamb Chops", category: "Meat", price: 9.5, quantity_type: "Lb", emoji: "🍖" },
  { name: "Ham", category: "Meat", price: 5.0, quantity_type: "Lb", emoji: "🍖" },
  { name: "Ribeye Steak", category: "Meat", price: 12.0, quantity_type: "Lb", emoji: "🥩" },
  { name: "Roast Beef", category: "Meat", price: 8.0, quantity_type: "Lb", emoji: "🥩" },
  { name: "Meatballs", category: "Meat", price: 6.0, quantity_type: "Lb", emoji: "🍖" },
  { name: "Hot Dogs", category: "Meat", price: 3.5, quantity_type: "Lb", emoji: "🌭" },
  { name: "Pepperoni", category: "Meat", price: 6.0, quantity_type: "Lb", emoji: "🍕" },
  { name: "Salami", category: "Meat", price: 6.5, quantity_type: "Lb", emoji: "🥓" },

  { name: "Salmon", category: "Seafood", price: 12.0, quantity_type: "Lb", emoji: "🐟" },
  { name: "Shrimp", category: "Seafood", price: 10.0, quantity_type: "Lb", emoji: "🍤" },
  { name: "Tuna", category: "Seafood", price: 9.0, quantity_type: "Lb", emoji: "🐟" },

  { name: "Eggs", category: "Dairy", price: 2.5, quantity_type: "Dozen", emoji: "🥚" },
  { name: "Rice", category: "Grains", price: 1.0, quantity_type: "Lb", emoji: "🍚" },
  { name: "Pasta", category: "Grains", price: 1.2, quantity_type: "Box", emoji: "🍝" },
  { name: "Oats", category: "Grains", price: 0.9, quantity_type: "Lb", emoji: "🥣" },
  { name: "Quinoa", category: "Grains", price: 2.5, quantity_type: "Lb", emoji: "🍚" },

  { name: "Black Beans", category: "Canned Goods", price: 1.0, quantity_type: "Each", emoji: "🫘" },
  { name: "Chickpeas", category: "Canned Goods", price: 1.1, quantity_type: "Each", emoji: "🧆" },
  { name: "Tomato Sauce", category: "Canned Goods", price: 1.2, quantity_type: "Each", emoji: "🍅" },

  { name: "Orange Juice", category: "Beverages", price: 3.0, quantity_type: "Liter", emoji: "🧃" },
  { name: "Coffee", category: "Beverages", price: 8.0, quantity_type: "Lb", emoji: "☕" },

  // Juice (new category)
  { name: "Apple Juice", category: "Juice", price: 3.0, quantity_type: "Liter", emoji: "🧃" },
  { name: "Grape Juice", category: "Juice", price: 3.2, quantity_type: "Liter", emoji: "🧃" },
  { name: "Cranberry Juice", category: "Juice", price: 3.5, quantity_type: "Liter", emoji: "🧃" },
  { name: "Pineapple Juice", category: "Juice", price: 3.3, quantity_type: "Liter", emoji: "🧃" },
  { name: "Mango Juice", category: "Juice", price: 3.4, quantity_type: "Liter", emoji: "🧃" },

  { name: "Tortilla Chips", category: "Snacks", price: 3.0, quantity_type: "Bag", emoji: "🌽" },
  { name: "Granola Bar", category: "Snacks", price: 0.9, quantity_type: "Each", emoji: "🍫" },

  { name: "Olive Oil", category: "Oils & Vinegars", price: 7.0, quantity_type: "Liter", emoji: "🫒" },
  { name: "Balsamic Vinegar", category: "Oils & Vinegars", price: 4.0, quantity_type: "Liter", emoji: "🧴" },

  { name: "Flour", category: "Baking", price: 2.0, quantity_type: "Lb", emoji: "🌾" },
  { name: "Sugar", category: "Baking", price: 1.8, quantity_type: "Lb", emoji: "🍬" },
  { name: "Baking Powder", category: "Baking", price: 1.5, quantity_type: "Each", emoji: "🧪" },

  { name: "Ketchup", category: "Condiments", price: 2.5, quantity_type: "Each", emoji: "🍅" },
  { name: "Mayonnaise", category: "Condiments", price: 3.0, quantity_type: "Each", emoji: "🥪" },
  { name: "Mustard", category: "Condiments", price: 2.0, quantity_type: "Each", emoji: "🌭" },

  // Fast Food Items
  { name: "Cheeseburger", category: "Fast Food", price: 4.99, quantity_type: "Each", emoji: "🍔" },
  { name: "Hamburger", category: "Fast Food", price: 3.99, quantity_type: "Each", emoji: "🍔" },
  { name: "Chicken Burger", category: "Fast Food", price: 5.49, quantity_type: "Each", emoji: "🍗" },
  { name: "Bacon Burger", category: "Fast Food", price: 6.99, quantity_type: "Each", emoji: "🥓" },
  { name: "Fish Burger", category: "Fast Food", price: 5.99, quantity_type: "Each", emoji: "🐟" },
  { name: "Veggie Burger", category: "Fast Food", price: 4.49, quantity_type: "Each", emoji: "🥬" },
  
  { name: "French Fries", category: "Fast Food", price: 2.99, quantity_type: "Each", emoji: "🍟" },
  { name: "Sweet Potato Fries", category: "Fast Food", price: 3.49, quantity_type: "Each", emoji: "🍠" },
  { name: "Onion Rings", category: "Fast Food", price: 3.99, quantity_type: "Each", emoji: "🧅" },
  { name: "Mozzarella Sticks", category: "Fast Food", price: 4.49, quantity_type: "Each", emoji: "🧀" },
  { name: "Chicken Nuggets", category: "Fast Food", price: 4.99, quantity_type: "Each", emoji: "🍗" },
  { name: "Chicken Wings", category: "Fast Food", price: 6.99, quantity_type: "Each", emoji: "🍗" },
  { name: "Chicken Tenders", category: "Fast Food", price: 5.49, quantity_type: "Each", emoji: "🍗" },
  
  { name: "Hot Dog", category: "Fast Food", price: 3.49, quantity_type: "Each", emoji: "🌭" },
  { name: "Chili Dog", category: "Fast Food", price: 4.49, quantity_type: "Each", emoji: "🌭" },
  { name: "Corn Dog", category: "Fast Food", price: 2.99, quantity_type: "Each", emoji: "🌽" },
  
  { name: "Pizza Slice", category: "Fast Food", price: 2.99, quantity_type: "Each", emoji: "🍕" },
  { name: "Pepperoni Pizza", category: "Fast Food", price: 12.99, quantity_type: "Each", emoji: "🍕" },
  { name: "Cheese Pizza", category: "Fast Food", price: 10.99, quantity_type: "Each", emoji: "🍕" },
  { name: "Supreme Pizza", category: "Fast Food", price: 15.99, quantity_type: "Each", emoji: "🍕" },
  
  { name: "Chicken Sandwich", category: "Fast Food", price: 5.99, quantity_type: "Each", emoji: "🥪" },
  { name: "BLT Sandwich", category: "Fast Food", price: 4.99, quantity_type: "Each", emoji: "🥪" },
  { name: "Club Sandwich", category: "Fast Food", price: 6.49, quantity_type: "Each", emoji: "🥪" },
  { name: "Grilled Cheese", category: "Fast Food", price: 3.99, quantity_type: "Each", emoji: "🧀" },
  
  { name: "Tacos", category: "Fast Food", price: 2.99, quantity_type: "Each", emoji: "🌮" },
  { name: "Burrito", category: "Fast Food", price: 6.99, quantity_type: "Each", emoji: "🌯" },
  { name: "Quesadilla", category: "Fast Food", price: 5.49, quantity_type: "Each", emoji: "🧀" },
  { name: "Nachos", category: "Fast Food", price: 4.99, quantity_type: "Each", emoji: "🧀" },
  
  { name: "Fried Chicken", category: "Fast Food", price: 7.99, quantity_type: "Each", emoji: "🍗" },
  { name: "Chicken Salad", category: "Fast Food", price: 6.99, quantity_type: "Each", emoji: "🥗" },
  { name: "Caesar Salad", category: "Fast Food", price: 5.99, quantity_type: "Each", emoji: "🥗" },
  { name: "Garden Salad", category: "Fast Food", price: 4.99, quantity_type: "Each", emoji: "🥗" },
  
  { name: "Milkshake", category: "Fast Food", price: 3.99, quantity_type: "Each", emoji: "🥤" },
  { name: "Soft Drink", category: "Fast Food", price: 1.99, quantity_type: "Each", emoji: "🥤" },
  { name: "Soda", category: "Fast Food", price: 1.99, quantity_type: "Each", emoji: "🥤" },
  { name: "Coca Cola", category: "Fast Food", price: 1.99, quantity_type: "Each", emoji: "🥤" },
  { name: "Pepsi", category: "Fast Food", price: 1.99, quantity_type: "Each", emoji: "🥤" },
  { name: "Sprite", category: "Fast Food", price: 1.99, quantity_type: "Each", emoji: "🥤" },
  { name: "Iced Tea", category: "Fast Food", price: 1.99, quantity_type: "Each", emoji: "🧊" },
  { name: "Coffee", category: "Fast Food", price: 1.49, quantity_type: "Each", emoji: "☕" },
  
  { name: "Ice Cream Cone", category: "Fast Food", price: 2.49, quantity_type: "Each", emoji: "🍦" },
  { name: "Ice Cream Sundae", category: "Fast Food", price: 3.99, quantity_type: "Each", emoji: "🍨" },
  { name: "Apple Pie", category: "Fast Food", price: 1.99, quantity_type: "Each", emoji: "🥧" },
  { name: "Chocolate Chip Cookie", category: "Fast Food", price: 1.49, quantity_type: "Each", emoji: "🍪" },
  { name: "Donut", category: "Fast Food", price: 1.29, quantity_type: "Each", emoji: "🍩" },
  { name: "Muffin", category: "Fast Food", price: 2.49, quantity_type: "Each", emoji: "🧁" },
];

export default foodItems